'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { AppShell } from '@/components/app-shell';
import { Badge, PageTitle, StatCard } from '@/components/ui';
import { Icon } from '@/components/icons';
import { CrudMenu, EmptyState, FormActions, Modal, Toast } from '@/components/crud-ui';
import { useWorkspace } from '@/lib/workspace';

type Ticket={id:string;room_id:string|null;title:string;description:string|null;priority:string;status:string;created_at:string;updated_at:string};
type Room={id:string;room_number:string;building_id:string|null};
type Building={id:string;name:string};
const emptyForm={room_id:'',title:'',description:'',priority:'medium',status:'open'};
const colDefs=[['open','ใหม่'],['in_progress','กำลังดำเนินการ'],['completed','เสร็จสิ้น']] as const;
const priLabel:Record<string,string>={low:'ต่ำ',medium:'กลาง',high:'สูง',urgent:'เร่งด่วน'};

export default function MaintenancePage(){
  const workspace=useWorkspace();
  const [tickets,setTickets]=useState<Ticket[]>([]); const [rooms,setRooms]=useState<Room[]>([]); const [buildings,setBuildings]=useState<Building[]>([]); const [buildingFilter,setBuildingFilter]=useState(''); const [open,setOpen]=useState(false); const [editing,setEditing]=useState<Ticket|null>(null); const [form,setForm]=useState(emptyForm); const [saving,setSaving]=useState(false); const [toast,setToast]=useState<{message:string;tone:'success'|'error'}|null>(null);
  async function load(){if(!workspace.supabase||!workspace.activePropertyId){setTickets([]);return;}const pid=workspace.activePropertyId;const [t,r,b]=await Promise.all([workspace.supabase.from('maintenance_tickets').select('id,room_id,title,description,priority,status,created_at,updated_at').eq('property_id',pid).order('created_at',{ascending:false}),workspace.supabase.from('rooms').select('id,room_number,building_id').eq('property_id',pid).is('archived_at',null).order('room_number'),workspace.supabase.from('buildings').select('id,name').eq('property_id',pid).order('name')]);if(t.error)setToast({message:t.error.message,tone:'error'});else setTickets((t.data||[]) as Ticket[]);setRooms((r.data||[]) as Room[]);setBuildings((b.data||[]) as Building[])}
  useEffect(()=>{setBuildingFilter('');void load();},[workspace.activePropertyId]); const roomMap=useMemo(()=>new Map(rooms.map(r=>[r.id,r.room_number])),[rooms]); const roomById=useMemo(()=>new Map(rooms.map(r=>[r.id,r])),[rooms]);
  function createNew(){setEditing(null);setForm(emptyForm);setOpen(true)} function editTicket(t:Ticket){setEditing(t);setForm({room_id:t.room_id||'',title:t.title,description:t.description||'',priority:t.priority,status:t.status});setOpen(true)}
  async function submit(e:FormEvent){e.preventDefault();if(!workspace.supabase||!workspace.activePropertyId)return;setSaving(true);const payload={room_id:form.room_id||null,title:form.title.trim(),description:form.description.trim()||null,priority:form.priority,status:form.status,updated_at:new Date().toISOString()};if(editing){const result=await workspace.supabase.from('maintenance_tickets').update(payload).eq('id',editing.id);if(result.error)setToast({message:result.error.message,tone:'error'});else{setToast({message:'แก้ไขงานซ่อมแล้ว',tone:'success'});setOpen(false);await load()}}else{const result=await workspace.supabase.from('maintenance_tickets').insert({...payload,property_id:workspace.activePropertyId}).select('id').single();if(result.error)setToast({message:result.error.message,tone:'error'});else{const roomNo=form.room_id?roomMap.get(form.room_id)||'-':'-';void fetch('/api/notifications/dispatch',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({propertyId:workspace.activePropertyId,eventKey:'maintenance_new',title:`แจ้งซ่อมใหม่ · ห้อง ${roomNo}`,body:form.title.trim(),severity:form.priority==='urgent'||form.priority==='high'?'error':'warning',entityType:'maintenance_ticket',entityId:result.data.id,dedupeKey:`maintenance-new:${result.data.id}`})});setToast({message:'สร้างงานซ่อมแล้ว',tone:'success'});setOpen(false);await load()}}setSaving(false)}
  async function remove(t:Ticket){if(!workspace.supabase||!window.confirm(`ลบงาน “${t.title}”?`))return;const {error}=await workspace.supabase.from('maintenance_tickets').delete().eq('id',t.id);if(error)setToast({message:error.message,tone:'error'});else{setToast({message:'ลบงานซ่อมแล้ว',tone:'success'});await load()}}
  async function quickStatus(t:Ticket,status:string){if(!workspace.supabase)return;const {error}=await workspace.supabase.from('maintenance_tickets').update({status,updated_at:new Date().toISOString()}).eq('id',t.id);if(error)setToast({message:error.message,tone:'error'});else await load()}
  const filteredTickets=tickets.filter(t=>!buildingFilter||(t.room_id?roomById.get(t.room_id)?.building_id===buildingFilter:false)); const filteredRooms=rooms.filter(r=>!buildingFilter||r.building_id===buildingFilter);
  const openCount=filteredTickets.filter(t=>t.status==='open').length, progress=filteredTickets.filter(t=>t.status==='in_progress').length, done=filteredTickets.filter(t=>t.status==='completed').length;
  return <AppShell><PageTitle title="แจ้งซ่อม" subtitle="จัดการงานซ่อมจริงจาก Supabase" action={workspace.can('maintenance.create')?<button className="primary-btn" onClick={createNew} disabled={!workspace.activePropertyId}><Icon name="plus" size={18}/> สร้างรายการ</button>:undefined}/><section className="stats-grid compact"><StatCard icon="wrench" label="งานทั้งหมด" value={`${filteredTickets.length} งาน`} note="รายการปัจจุบัน"/><StatCard icon="bell" label="งานใหม่" value={`${openCount} งาน`} note="ต้องตรวจสอบ" tone="amber"/><StatCard icon="settings" label="กำลังซ่อม" value={`${progress} งาน`} note="อยู่ระหว่างดำเนินการ" tone="blue"/><StatCard icon="chart" label="ปิดงานแล้ว" value={`${done} งาน`} note="เสร็จสิ้น" tone="green"/></section>
  <div className="toolbar"><div className="meter-filter-group"><label className="building-filter"><Icon name="project" size={17}/><span>อาคาร</span><select value={buildingFilter} onChange={e=>setBuildingFilter(e.target.value)}><option value="">ทุกอาคาร ({rooms.length})</option>{buildings.map(b=><option key={b.id} value={b.id}>{b.name} ({rooms.filter(r=>r.building_id===b.id).length} ห้อง)</option>)}</select><Icon name="chevron-down" size={15}/></label></div></div>
  {!workspace.activePropertyId?<EmptyState title="ยังไม่มีโครงการ" description="สร้างโครงการก่อนเพิ่มงานซ่อม"/>:!filteredTickets.length?<EmptyState title="ยังไม่มีงานซ่อม" description="กดสร้างรายการเพื่อเพิ่มงานแรก" action={workspace.can('maintenance.create')?<button className="primary-btn" onClick={createNew}><Icon name="plus" size={17}/> สร้างรายการ</button>:undefined}/>:<div className="ticket-board">{colDefs.map(([key,col])=><section className="ticket-column" key={key}><div className="ticket-col-head"><h3>{col}</h3><span>{filteredTickets.filter(t=>t.status===key).length}</span></div>{filteredTickets.filter(t=>t.status===key).map(t=><article className="ticket-card" key={t.id}><div className="ticket-id">{t.id.slice(0,8).toUpperCase()}<Badge tone={t.priority==='high'||t.priority==='urgent'?'red':t.priority==='medium'?'amber':'gray'}>{priLabel[t.priority]||t.priority}</Badge></div><h4>{t.title}</h4><p>ห้อง {t.room_id?roomMap.get(t.room_id)||'-':'-'} · {t.description||'ไม่มีรายละเอียด'}</p><div className="ticket-foot"><span>{new Date(t.created_at).toLocaleDateString('th-TH')}</span><div className="ticket-inline-actions">{workspace.can('maintenance.update')&&key==='open'&&<button onClick={()=>void quickStatus(t,'in_progress')}>เริ่มงาน</button>}{workspace.can('maintenance.update')&&key==='in_progress'&&<button onClick={()=>void quickStatus(t,'completed')}>ปิดงาน</button>}<CrudMenu canEdit={workspace.can('maintenance.update')} canDelete={workspace.can('maintenance.delete')} onEdit={()=>editTicket(t)} onDelete={()=>void remove(t)}/></div></div></article>)}</section>)}</div>}
  <Modal open={open} title={editing?'แก้ไขงานซ่อม':'สร้างงานซ่อม'} onClose={()=>setOpen(false)}><form className="crud-form" onSubmit={submit}><div className="form-grid"><label>ห้อง<select value={form.room_id} onChange={e=>setForm({...form,room_id:e.target.value})}><option value="">ไม่ระบุห้อง</option>{filteredRooms.map(r=><option key={r.id} value={r.id}>ห้อง {r.room_number}</option>)}</select></label><label>ความสำคัญ<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option value="low">ต่ำ</option><option value="medium">กลาง</option><option value="high">สูง</option><option value="urgent">เร่งด่วน</option></select></label><label className="full">หัวข้องาน<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label className="full">รายละเอียด<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>สถานะ<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="open">ใหม่</option><option value="in_progress">กำลังดำเนินการ</option><option value="completed">เสร็จสิ้น</option><option value="cancelled">ยกเลิก</option></select></label></div><FormActions saving={saving} onCancel={()=>setOpen(false)}/></form></Modal><Toast message={toast?.message||null} tone={toast?.tone} onClose={()=>setToast(null)}/></AppShell>
}
