'use client';

import { FormEvent, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { AppShell } from '@/components/app-shell';
import { EmptyState, Toast } from '@/components/crud-ui';
import { PageTitle } from '@/components/ui';
import { useWorkspace } from '@/lib/workspace';
import { Icon } from '@/components/icons';
import { NotificationSettings } from '@/components/notification-settings';
import { DiscordMeterSettings } from '@/components/discord-meter-settings';

const empty={name:'',phone:'',address:'',billing_day:'25',due_day:'5',electricity_rate:'8',water_rate:'28',water_minimum_charge:'150',water_service_fee:'10',meter_high_usage_water:'30',meter_high_usage_electricity:'300'};
export default function SettingsPage(){
  const router=useRouter();
  const workspace=useWorkspace(); const canManage=workspace.can('settings.manage'); const canManageNotifications=workspace.can('notifications.manage'); const [form,setForm]=useState(empty); const [saving,setSaving]=useState(false); const [toast,setToast]=useState<{message:string;tone:'success'|'error'}|null>(null);
  useEffect(()=>{const p=workspace.activeProperty;if(p)setForm({name:p.name||'',phone:p.phone||'',address:p.address||'',billing_day:String(p.billing_day??25),due_day:String(p.due_day??5),electricity_rate:String(p.electricity_rate??8),water_rate:String(p.water_rate??28),water_minimum_charge:String(p.water_minimum_charge??0),water_service_fee:String(p.water_service_fee??0),meter_high_usage_water:String(p.meter_high_usage_water??30),meter_high_usage_electricity:String(p.meter_high_usage_electricity??300)})},[workspace.activePropertyId,workspace.activeProperty]);
  async function logout(){try {if(workspace.supabase) await workspace.supabase.auth.signOut({scope:'local'});} finally {window.localStorage.removeItem('dormplus.activePropertyId');router.replace('/login');router.refresh();}}
  async function submit(e:FormEvent){e.preventDefault();if(!workspace.supabase||!workspace.activePropertyId)return;setSaving(true);const {error}=await workspace.supabase.from('properties').update({name:form.name.trim(),phone:form.phone.trim()||null,address:form.address.trim()||null,billing_day:Number(form.billing_day),due_day:Number(form.due_day),electricity_rate:Number(form.electricity_rate),water_rate:Number(form.water_rate),water_minimum_charge:Number(form.water_minimum_charge)||0,water_service_fee:Number(form.water_service_fee)||0,meter_high_usage_water:Number(form.meter_high_usage_water)||0,meter_high_usage_electricity:Number(form.meter_high_usage_electricity)||0,updated_at:new Date().toISOString()}).eq('id',workspace.activePropertyId);if(error)setToast({message:error.message,tone:'error'});else{setToast({message:'บันทึกการตั้งค่าแล้ว',tone:'success'});await workspace.refresh()}setSaving(false)}
  return <AppShell><PageTitle title="ตั้งค่าระบบ" subtitle="ข้อมูลโครงการ รอบบิล อัตราน้ำไฟ เกณฑ์มิเตอร์ และช่องทางแจ้งเตือน"/>{!workspace.activePropertyId?<EmptyState title="ยังไม่มีโครงการ" description="สร้างโครงการก่อนตั้งค่าระบบ"/>:<form onSubmit={submit}><div className="settings-grid"><section className="panel form-panel"><h3>ข้อมูลโครงการ</h3><div className="form-grid"><label>ชื่อโครงการ<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>เบอร์โทร<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label className="full">ที่อยู่<input value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label></div></section><section className="panel form-panel"><h3>รอบบิลและค่าน้ำไฟ</h3><div className="form-grid"><label>วันที่ออกบิล<input type="number" min="1" max="28" value={form.billing_day} onChange={e=>setForm({...form,billing_day:e.target.value})}/></label><label>วันครบกำหนด<input type="number" min="1" max="28" value={form.due_day} onChange={e=>setForm({...form,due_day:e.target.value})}/></label><label>ค่าไฟ / หน่วย<input type="number" min="0" step="0.01" value={form.electricity_rate} onChange={e=>setForm({...form,electricity_rate:e.target.value})}/></label><label>ค่าน้ำ / หน่วย<input type="number" min="0" step="0.01" value={form.water_rate} onChange={e=>setForm({...form,water_rate:e.target.value})}/></label><label>ขั้นต่ำค่าน้ำ<input type="number" min="0" step="0.01" value={form.water_minimum_charge} onChange={e=>setForm({...form,water_minimum_charge:e.target.value})}/></label><label>ค่าบริการน้ำ<input type="number" min="0" step="0.01" value={form.water_service_fee} onChange={e=>setForm({...form,water_service_fee:e.target.value})}/></label></div></section><section className="panel form-panel full-settings-panel"><h3>เกณฑ์แจ้งเตือนมิเตอร์</h3><p className="settings-help">เมื่อบันทึกหน่วยใช้งานเกินเกณฑ์ ระบบจะส่งเหตุการณ์ “มิเตอร์ผิดปกติ” ไปยังช่องทางที่เปิดไว้</p><div className="form-grid"><label>น้ำเกิน (หน่วย/เดือน)<input type="number" min="0" step="0.01" value={form.meter_high_usage_water} onChange={e=>setForm({...form,meter_high_usage_water:e.target.value})}/></label><label>ไฟเกิน (หน่วย/เดือน)<input type="number" min="0" step="0.01" value={form.meter_high_usage_electricity} onChange={e=>setForm({...form,meter_high_usage_electricity:e.target.value})}/></label></div>{canManage?<button className="primary-btn" type="submit" disabled={saving}>{saving?'กำลังบันทึก...':'บันทึกการตั้งค่า'}</button>:<p className="settings-readonly-note">คุณมีสิทธิ์ดูการตั้งค่า แต่ไม่มีสิทธิ์แก้ไข</p>}</section></div></form>}
  {canManage&&<DiscordMeterSettings onMessage={(message,tone)=>setToast({message,tone})}/>}
  {canManageNotifications&&<NotificationSettings onMessage={(message,tone)=>setToast({message,tone})}/>}
  {!canManage&&!canManageNotifications&&<section className="panel settings-readonly-panel"><Icon name="shield" size={20}/><div><b>โหมดดูอย่างเดียว</b><span>Owner หรือ Role ที่มีสิทธิ์ settings.manage / notifications.manage จึงจะเปลี่ยน Integration และการแจ้งเตือนได้</span></div></section>}
  <section className="panel account-panel"><div><span className="settings-kicker">บัญชีผู้ใช้งาน</span><h3>การเข้าสู่ระบบ</h3><p>ออกจากระบบบนอุปกรณ์นี้ แล้วกลับไปยังหน้า Login</p></div><button type="button" className="danger-outline-btn" onClick={logout}><Icon name="logout" size={17}/> ออกจากระบบ</button></section><Toast message={toast?.message||null} tone={toast?.tone} onClose={()=>setToast(null)}/></AppShell>
}
